name: securityexperts_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_database: ^12.1.0
  flutter_local_notifications: ^17.0.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  file_picker: ^10.3.0
  path: ^1.9.0
  url_launcher: ^6.1.10
  video_player: ^2.8.5
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.4.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  audioplayers: ^6.5.1
  flutter_linkify: ^6.0.0
  flutter_image_compress: ^2.4.0
  photo_manager: ^3.6.3
  image: ^4.1.7
  http: ^1.2.2
  permission_handler: ^11.0.1
  image_picker: ^1.0.7
  record: ^5.1.2
  camera: ^0.11.3
  shared_preferences: ^2.2.0
  local_auth: ^2.1.8
  google_fonts: ^6.2.0
  wakelock_plus: ^1.2.4
  scrollable_positioned_list: ^0.3.8
  firebase_remote_config: ^6.1.2
  cloud_functions: ^6.0.4
  livekit_client: ^2.6.1
  get_it: ^7.6.0
  firebase_crashlytics: ^5.0.5
  firebase_analytics: ^12.0.4
  firebase_performance: ^0.11.1+4
  provider: ^6.1.5+1
  equatable: ^2.0.8
  uuid: ^4.5.1
  intl: ^0.19.0
  device_info_plus: ^12.3.0
  package_info_plus: ^8.0.0
  any_link_preview: ^3.0.3
  shimmer: ^3.0.0
  flutter_radio_group: ^2.1.0
  syncfusion_flutter_pdfviewer: ^32.1.25
  shake_detector: ^0.0.1


dependency_overrides:
  record_linux: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.15.1
  build_runner: ^2.4.13
  test: ^1.25.0
  fake_cloud_firestore: ^4.0.1
  firebase_storage_mocks: ^0.8.0+1
  path_provider_platform_interface: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/sounds/ringtone.mp3
    - assets/sounds/ringtone1.mp3
    - assets/profanity/
    - assets/data/
